// src/frontend/components/List.vue
<template>
  <div class="list x">
    <div v-for="item in items" class="user">
      <span className="main">
      {{ item.displayName }}
      </span>
      <a href="#" @click="getUser(item.id)">details</a>
    </div>
  </div>
</template>


<script>
import { mapGetters, mapActions } from 'vuex'
export default {
  computed: mapGetters({
    items: 'list'
  }),
  methods: mapActions([
    'getUser'
  ]),
  created () {
    this.$store.dispatch('getList')
  }
}
</script>

// src/frontend/components/list.jsx
import React, {PropTypes} from "react"

function listItems(items){
  return items.map(item =>
    <div key={item.id} className="user">
    <span className="main">
    {item.displayName}
    </span>
    <a href={"#"+item.id}>details</a>
    </div>)
}

const List = ((props) =>
    (<div className="list">
      {listItems(props.items)}
    </div>))

List.propTypes = {
  items: PropTypes.array.isRequired
}

export default List
