// src/frontend/components/user.jsx
import React, {PropTypes} from "react"


const User = ((props) =>
    (<div className="user">
      <ul>
        <li className="name">{props.username}</li>
        <li>name: {props.displayName}</li>
        <li>twitter: {props.twitter}</li>
        <li>memberFor: {props.memberFor}</li>
      </ul>
    </div>))

User.propTypes = {
  username: PropTypes.string.isRequired,
  displayName: PropTypes.string.isRequired,
  twitter: PropTypes.string.isRequired,
  memberFor: PropTypes.string.isRequired,
}

export default User

// src/frontend/components/User.vue
<template>
  <div  v-show="!!user.username" class="user">
    <ul>
      <li class="name">{{ user.username }}</li>
      <li>name: {{ user.displayName }}</li>
      <li>twitter: {{ user.twitter }}</li>
      <li>memberFor: {{ user.memberFor }}</li>
    </ul>
  </div>
</template>


<script>
import { mapGetters, mapActions } from 'vuex'
export default {
  computed: mapGetters({
    user: 'user'
  })
}
</script>
